// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Relude from "relude/src/Relude.bs.js";
import * as Relude_List from "relude/src/Relude_List.bs.js";

console.log(Relude_List.toArray(/* [] */0));

export {
  
}
/*  Not a pure module */
